name: mygentic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - selenium
  - jupyter
  - matplotlib
  - pandas
  - numpy
  - ipykernel
  - requests
  - beautifulsoup4
  - loguru
  - tqdm
  - google-generativeai
  - python-dotenv
  - rich
  - pip
  - pip:
    - itables
    - pydantic-ai
    - crewai
    - firecrawl-py
